name: "github-oidc"

on:
  push:
    branches:
      - main
      #- develop
    paths:
      - "projects/github-oidc/**"
      - ".github/workflows/github-oidc.yaml"
env:
  CI: "true"
  TESTING_STACK_NAME: "infra-github-oidc-dev"
  GITHUB_ASSUME_ROLE: arn:aws:iam::037729278610:role/github-deploy-role
  TESTING_REGION: ap-northeast-2
  PROD_STACK_NAME: "infra-github-oidc-prod"
  PROD_REGION: ap-northeast-2


jobs:
  cdk_build:
    runs-on: ubuntu-latest
     # These permissions are needed to interact with GitHub's OIDC Token endpoint
    permissions:
      id-token: write
      contents: read
    env:
      CI: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: projects/github-oidc

      - name: Install dependencies
        run : npm run projen
        working-directory: projects/github-oidc

      - name: assume role
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.GITHUB_ASSUME_ROLE }}
          role-session-name: github-session
          aws-region: ap-northeast-2

      - name: cdk diff
        run: npm run diff
        working-directory: projects/github-oidc

      - name: cdk build 
        run: npm run build 
        working-directory: projects/github-oidc
          
      - name: cdk deploy
        run: npm run deploy --all --require-approval never
        working-directory: projects/github-oidc
